name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: $AZURE_CREDENTIALS

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: $REGISTRY_LOGIN_SERVER
          username: $REGISTRY_USERNAME
          password: $REGISTRY_PASSWORD
      - run: |
          docker build ./azure-web-api -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$GITHUI_REPOSITORY:$GITHUB_RUN_ID
          docker push $REGISTRY_LOGIN_SERVER/$GITHUI_REPOSITORY:$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: $AZURE_CREDENTIALS

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: $RESOURCE_GROUP
          dns-name-label: aztek-azure-web-api
          image: $REGISTRY_LOGIN_SERVER/$GITHUI_REPOSITORY:$GITHUB_RUN_ID
          registry-login-server: $REGISTRY_LOGIN_SERVER
          registry-username: $REGISTRY_USERNAME
          registry-password: $REGISTRY_PASSWORD
          name: aztek-azure-web-api-container
          location: "brazilsouth"
